### ISSUE TITLE
Not work

### ISSUE THREAD

**Issue by angelru** [umair-me/BlazorServer-BootstrapSelect#1]
Hello, this example in WASM not working...

**Comment by umair-me** [comment]
Hello, whats not working?

**Comment by angelru** [comment]
It is as if every time I enter the page where the select is, it is created again and multiple selects

**Comment by angelru** [comment]
@umair-me too happens in your sample
![Captura](https://user-images.githubusercontent.com/11645585/114504624-72e5f080-9c2f-11eb-9ffd-bb2539813c01.PNG)
